Repository ramzini22/passim_chat_service, pull requests merged in 2024-12, with the labels that each got.

#29 fix: fixed invalid method sorting message in method fidChat
  src/modules/chats/services/chats.service.ts
Labels: bug, invalid

#30 feature: add decorator for relations for swagger
  api/swagger.json
  src/modules/chats/entities/chat.entity.ts
  src/modules/chats/entities/message.entity.ts
Labels: bug, documentation

#32 feature: add kafka in env.example
  .env.example
Labels: invalid

#34 18 добавить функционал для прослушивания чатов
  api/swagger.json
  src/common/swagger/api-data-array-numbers.decorator.ts
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/services/chats.service.ts
  src/modules/queue/types/events.enum.ts
Labels: enhancement

#35 feature: add relation in method createOpenChat
  api/swagger.json
  src/modules/chats/services/chats.service.ts
Labels: good first issue

#39 refactor: queue.service
  api/swagger.json
  src/modules/chats/services/chats.service.ts
  src/modules/chats/services/messages.service.ts
  src/modules/queue/queue.service.ts
  src/modules/queue/types/topics.enum.ts
Labels: good first issue

#42 bug: param socketId in method favoritesChats is required
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/services/chats.service.ts
Labels: bug

#44 feature: add method search ilike
  api/swagger.json
  src/modules/chats/services/chats.service.ts
Labels: enhancement

#47 feature: add index GIN + migrat
  src/migrations/Migration20241220190654_index_title.ts
  src/modules/chats/entities/chat.entity.ts
Labels: enhancement

#49 fix: fixed bug search
  src/modules/chats/services/chats.service.ts
Labels: bug

#51 37 доработать метод получения чатов
  api/swagger.json
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/dto/requests/query-get-chats.dto.ts
  src/modules/chats/services/chats.service.ts
Labels: enhancement

#53 fix: add fast update chat count_messages
  src/modules/chats/services/messages.service.ts
Labels: bug

#54 refactor: change messages to message
  api/swagger.json
  src/modules/chats/entities/chat.entity.ts
  src/modules/chats/entities/message.entity.ts
  src/modules/chats/services/chats.service.ts
Labels: enhancement

#55 feature: changed id to uuid + add migra
  api/swagger.json
  package-lock.json
  package.json
  src/common/entities/base.entity.ts
  src/migrations/Migration20241224192916_changed_id_to_uuid.ts
  src/modules/app.module.ts
  src/modules/chats/chats.module.ts
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/dto/requests/create-post-message.dto.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/dto/requests/query-get-chats.dto.ts
  src/modules/chats/dto/requests/query-get-messages.dto.ts
  src/modules/chats/entities/chat-members.entity.ts
  src/modules/chats/entities/message.entity.ts
  src/modules/chats/services/chats.service.ts
  src/modules/chats/services/messages.service.ts
  src/modules/users/entities/user.entity.ts
  src/modules/users/users.module.ts
Labels: documentation, enhancement

#57 fix: correct validation and migration
  src/migrations/Migration20241224192916_changed_id_to_uuid.ts
  src/modules/chats/dto/requests/create-post-message.dto.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/dto/requests/query-get-chats.dto.ts
Labels: bug

#58 feature: create index search messages + add Migration_Index_search_me…
  api/swagger.json
  src/migrations/Migration20241225131344_Index_search_messages.ts
  src/modules/chats/entities/message.entity.ts
  src/modules/chats/services/messages.service.ts
Labels: enhancement
