Repository ramzini22/passim_chat_service, pull requests merged in 2025-01, with the labels that each got.

#61 feature: get last messages on a new connection
  api/swagger.json
  src/common/swagger/api-data.decorator.ts
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/entities/chat.entity.ts
  src/modules/chats/services/chats.service.ts
Labels: enhancement

#64 refactor: improve method and change response
  api/swagger.json
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/controllers/messages.controller.ts
  src/modules/chats/dto/requests/create-open-chat.dto.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/dto/requests/query-get-messages.dto.ts
  src/modules/chats/services/chats.service.ts
Labels: good first issue

#65 feature: add method leave
  api/swagger.json
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/dto/requests/post-favorites-chat.dto.ts
  src/modules/chats/dto/requests/post-leave-chat.dto.ts
  src/modules/chats/services/chats.service.ts
  src/modules/queue/types/events.enum.ts
  src/modules/queue/types/topics.enum.ts
Labels: enhancement

#67 refactor: add response
  api/swagger.json
  src/common/swagger/api-data-empty.decorator.ts
  src/modules/chats/controllers/chats.controller.ts
  src/modules/chats/services/chats.service.ts
Labels: bug
